name: flutter_linkify_example
description: flutter_linkify example

version: 1.0.0+1
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.2
  flutter_linkify:
    path: ..

flutter:
  uses-material-design: true
